### ISSUE TITLE
Geolite URL invalid

### ISSUE THREAD

**Issue by geek-at** [bunkerity/bunkerized-nginx#1]
In your [geolite.sh](https://github.com/bunkerity/bunkerized-nginx/blob/master/scripts/geolite.sh) there is a URL which is dead

**Comment by bunkerity** [comment]
Thanks for your report.

Fix will be integrated in the next release. MaxMind doesn't allow anymore to use their DB for free so let's stick with [db-ip.com](https://db-ip.com/db/download/ip-to-country-lite).

**Comment by bunkerity** [comment]
Fixed in the new version.
