### ISSUE TITLE
Proxy to another Server

### ISSUE THREAD

**Issue by ptr1337** [bunkerity/bunkerized-nginx#108]
For example, i own the certificate with the reverse proxy. 
So mostly i only need a http connection to my reverse proxy with 192.432.1.23 for example. 
is this possible?

regards

**Comment by bunkerity** [comment]
Hi @ptr1337,

Yes you can use bunkerized-nginx as a reverse proxy, here is more info : 
* [Basics](https://github.com/bunkerity/bunkerized-nginx#as-a-reverse-proxy)
* [Multisite support](https://github.com/bunkerity/bunkerized-nginx#multisite)
* [Compose examples](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples)

Does that meet your needs ?

**Comment by ptr1337** [comment]
Hey @bunkerity 

Yes, mostly i understand it. So bunkerity nginx and his security features would be perfect for using as reverse proxy for server/hosts which are not in the same network.
The profit would be hiding the ip of the origin server, load balancing, and a nice waf. 

The Question is also how to act because SSL, its enough to have a certificate on the reverse proxy right ?
Then im pointing on the origins servers ip . 
Is in the example below just the "proxy_pass" header set and i can control the nginx configuration from my server on my own?
Because im running a forum and want to add a extra security layer. 
Sorry for my bad english and thanks for your help. 

  myreverse:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - MULTISITE=yes
      - SERVER_NAME=app1.website.com app2.website.com # replace with your domain
      - SERVE_FILES=no
      - DISABLE_DEFAULT_SERVER=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - AUTO_LETS_ENCRYPT=yes
      - USE_PROXY_CACHE=yes
      - USE_GZIP=yes
      - USE_BROTLI=yes
      - USE_REVERSE_PROXY=yes
      - app1.website.com_REVERSE_PROXY_URL=/
      - app1.website.com_REVERSE_PROXY_HOST=http://123.123.123.123 (with port or without)
      - app2.website.com_REVERSE_PROXY_URL=/
      - app2.website.com_REVERSE_PROXY_HOST=http://124.124.124.124

**Comment by bunkerity** [comment]
If you want to add TLS on the proxied applications you need to do it by yourself inside this application. Maybe Let's Encrypt with an alternative domain name ? Or self signed / your own PKI ?

You should be able to add custom headers to the proxied application using the `REVERSE_PROXY_HEADERS` environment variable. Something like this : 
```yaml
- app1.website.com_REVERSE_PROXY_HEADERS=MyCustomHeader1 MyValue1;MyCustomHeader2 MyValue2
```
I didn't perform a full test on this feature, feel free to report any bug.

**Comment by bunkerity** [comment]
Closing this because REVERSE_PROXY_HEADERS should do the trick. Don't hesitate to open a new issue if needed.
