### ISSUE TITLE
Run unprivileged

### ISSUE THREAD

**Issue by e-minguez** [bunkerity/bunkerized-nginx#11]
Just like the nginx-unprivileged container image https://github.com/nginxinc/docker-nginx-unprivileged it would be nice if:

- The nginx process listen in a high unprivileged port
- Run as a regular user instead of root... or even better, [support arbitrary user ids](https://docs.openshift.com/container-platform/4.5/openshift_images/create-images.html#images-create-guide-openshift_create-images)

**Comment by bunkerity** [comment]
Hello @e-minguez, fix has been integrated in version [1.1.0](https://github.com/bunkerity/bunkerized-nginx/releases/tag/v1.1.0).

Nginx master process is not executed as root anymore and it listens on 8080 and 8443 unprivileged ports. Feel free to open a new issue if you think we can improve it.
