### ISSUE TITLE
Whitelist URI (e.g. callbacks)

### ISSUE THREAD

**Issue by JustDevZero** [bunkerity/bunkerized-nginx#110]
Hello,

I can't see this on the Readme. Therefore I'm asking.

I have a site that is using Redsys to receive payments. Redsys basically makes you a Post to an URL with a lot of data that you should decrypt and use it to confirm if anything was bought.

This callback is not being received on Django, but looks like nginx/waf thingy is basically destroying that callback

When I used Cloudflare on the past I used to have to write this in order to make it work :

![IMG-20210402-WA0001](https://user-images.githubusercontent.com/172759/113412010-808db180-93b7-11eb-802f-5dfec111b4f4.jpg)

But I don't know how I suppose to add some exception, neither by the asn neither by the uri.

Any ideas on that?

Many thanks

**Comment by JustDevZero** [comment]
Nevermind, this wasn't the problem. I'll close this.

**Comment by bunkerity** [comment]
I think that's a good feature anyway !

**Comment by JustDevZero** [comment]
Oh, cool to know that this is going to be a new feature! :D

**Comment by bunkerity** [comment]
Hello @JustDevZero,

With the last version, you can now use the `WHITELIST_URI` to whitelist URIs like callbacks. More info [here](https://github.com/bunkerity/bunkerized-nginx#custom-whitelisting). Don't hesitate to open a new issue if needed.
