### ISSUE TITLE
WHITELIST_USER_AGENT values

### ISSUE THREAD

**Issue by Kubilai12** [bunkerity/bunkerized-nginx#118]
Hi 

Can someone explain me how i put a value for authorize agent ? I don understand "list of regexes separated with spaces" there is sample model ?

WHITELIST_USER_AGENT
Values : <list of regexes separated with spaces>
Default value :
Context : global, multisite
Whitelist user agent from being blocked by BLOCK_USER_AGENT

Thanks a lot

**Comment by mromanelli9** [comment]
Hi. I haven't used it myself, but I think it takes a list of Lua  patterns (regular expressions), as you can see in [main-lua.conf](https://github.com/bunkerity/bunkerized-nginx/blob/afc66788556015889936164c9298640a1d191fe7/confs/site/main-lua.conf#L33).
For example, to allow default Goose user agent (`Goose/3.1.8`)  I'd use:
```
WHITELIST_USER_AGENT="^Goose"
```

**Comment by bunkerity** [comment]
Hello @Kubilai12,

This is exactly what @mromanelli9 said. Here is a quick example to illustrate it.

Without WHITELIST_USER_AGENT : 
```shell
$ docker run -d --rm -p 8080:8080 -v /tmp/www:/www bunkerity/bunkerized-nginx
$ curl -H "User-Agent: Scanbot 42" http://localhost:8080
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
$ curl -H "User-Agent: Evil/v1" http://localhost:8080
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

With WHITELIST_USER_AGENT : 
```shell
$ docker run -d --rm -p 8080:8080 -v /tmp/www:/www -e "WHITELIST_USER_AGENT=^Scanbot ^Evil" bunkerity/bunkerized-nginx
$ curl -H "User-Agent: Scanbot 42" http://localhost:8080
it works
$ curl -H "User-Agent: Evil/v1" http://localhost:8080
it works
```
