### ISSUE TITLE
Reverse Proxy : Upstream Servers error.

### ISSUE THREAD

**Issue by sbmandava** [bunkerity/bunkerized-nginx#12]
Trying to see if we can add multiple upstream load balancing servers.

upstream.conf

upstream xss-app {
        least_conn;
        server docker_xss-app_1:4001;
        server docker_xss-app_2:4001;
        server docker_xss-app_3:4001;
}

with reverse_proxy.conf referring to

proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

location / {
        proxy_pass http://xss-app$request_uri;
}

Logs show the following error
nginx: [emerg] "upstream" directive is not allowed here in /server-confs/upstream.conf:1

**Comment by bunkerity** [comment]
Hello @sbmandava, looks like the [upstream directive](https://nginx.org/en/docs/http/ngx_http_upstream_module.html#upstream) must be set at **http** context. Can you try to mount the folder containing **upstream.conf** at /http-confs ?

**Comment by sbmandava** [comment]
Thank you moving the upstream.conf to /http-confs resolved the issue.
