### ISSUE TITLE
Custom certificate intermediate

### ISSUE THREAD

**Issue by Kubilai12** [bunkerity/bunkerized-nginx#120]
Hi

if i use custom cert how can i put intermediate certifcate for solve this : "this servers certificate chain is incomplete" ? 

Docker Environnement variable have only 2 file to provide .crt and .key

**Comment by bunkerity** [comment]
Hi @Kubilai12,

Looks like nginx doesn't have a directive to provide intermediate certificate(s) (see [here](https://nginx.org/en/docs/http/configuring_https_servers.html)). Looks like you need to do a bundle (more info [here](https://nginx.org/en/docs/http/configuring_https_servers.html#chains)) of both server and intermediate certificates (order seems important be careful) and use it as the certificate with the CUSTOM_HTTPS_CERT env var.

**Comment by Kubilai12** [comment]
I follow this method : [](https://www.petenetlive.com/KB/Article/0001570)

All it s ok now

Thanks so much

**Comment by bunkerity** [comment]
Hello @Kubilai12,

I have updated the documentation in case someone else has the same problem.
