### ISSUE TITLE
/opt/scripts/proxies.sh runs for a very long time

### ISSUE THREAD

**Issue by adren** [bunkerity/bunkerized-nginx#121]
Building-up the block-proxies.conf file a launch from the iplists.firehol.org takes a very long time 

The loop in the shell script is sub-optimal in building the list, because it echoes one line at a time and greps for an IPv4 pattern for every single line, hence launching million of subshells.
The file is nearly 1.7M line (at the time of this writing) and on a quite powerful machine (8 cores i7) it takes 1 hour to generate the file.

With a single grep (instead of 1.7 millions) and a sed, the file can be processed in less than a second without any difference in the output (patch coming)

With this change, the script doesn't need to be run in background anymore

**Comment by adren** [comment]
this issue is addressed by #122

**Comment by adren** [comment]
check also #123 #124 #125 and #126

**Comment by bunkerity** [comment]
Hello @adren,

Thanks a lot for your work. This is a huge performance improvement ! I've edited it a little bit (see [this commit](https://github.com/bunkerity/bunkerized-nginx/commit/83841b290a53f074d47b20395032db1caf37b003)) and it works like a charm ! Changes are still on dev branch, let's keep this issue open until it's integrated into the next release.

**Comment by bunkerity** [comment]
Integrated into the last v1.2.5 version alongside others performance improvements. Thanks again @adren !
