### ISSUE TITLE
add "sandbox allow-downloads" to default CONTENT_SECURITY_POLICY value

### ISSUE THREAD

**Issue by mwester117** [bunkerity/bunkerized-nginx#130]
Hello,

if you use bunkerized-nginx as a reverse proxy for an application that offers file downloads, the Content-Security-Policy Header has to be modified.

The option "sandbox allow-downloads" must be added.

If you don't add it file downloads are blocked. The debugging is really difficult because no errors are logged.

Does it make sense to add "allow-downloads" to the default configuration? For example you could extend the default value to: "object-src 'none'; frame-ancestors 'self'; form-action 'self'; block-all-mixed-content; sandbox allow-forms allow-same-origin allow-scripts allow-popups allow-downloads; base-uri 'self'"

Perhaps some of the examples also need to be adjusted to support file downloads.

**Comment by bunkerity** [comment]
Integrated into the last v1.2.5 version. Thanks for your report @mwester117.
