### ISSUE TITLE
PROPFIND/PUT Option is not allowed 

### ISSUE THREAD

**Issue by dan-m8t** [bunkerity/bunkerized-nginx#133]
Hey there,

I am trying to use bunkerized-nginx as a reverse proxy in front of a nextcloud instance, every time I try to preview a file or even connect via the desktop client I get an forbidden 403 bei mod security I think.
I used the examples in this GitHub repo and already took a search and found this solution: #104 

That didn't help in my case.

Here are the logs:

`---pl6Gynkr---H--
ModSecurity: Warning. Matched "Operator `Within' with parameter `GET HEAD POST OPTIONS' against variable `REQUEST_METHOD' (Value: `PROPFIND' ) [file "/opt/owasp/crs/REQUEST-911-METHOD-ENFORCEMENT.conf"] [line "27"] [id "911100"] [rev ""] [msg "Method is not allowed by policy"] [data "PROPFIND"] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272/220/274"] [tag "PCI/12.1"] [hostname "10.0.2.100"] [uri "/remote.php/dav/files/admin/Talk"] [unique_id "162107945753.170953"] [ref "v0,8"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/opt/owasp/crs/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "10.0.2.100"] [uri "/remote.php/dav/files/admin/Talk"] [unique_id "162107945753.170953"] [ref ""]

---pl6Gynkr---Z--`

Here is my docker-compose file (anyways I am running CentOS8 with Podman and Podman-compose):

> version: '3'

> services:

>  mywww:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./certs:/etc/letsencrypt:z
      - ./server-confs:/server-confs:ro         # custom nginx confs at server context to make Nextcloud working
      - ./modsec-crs-confs:/modsec-crs-confs:ro # custom Core Rule Set confs to add Nextcloud exclusions
      - ./modsec-confs:/modsec-confs:ro         # disable some false positive
    environment:
      - SERVER_NAME=my.nextcloud.com          # replace with your domain
      - AUTO_LETS_ENCRYPT=yes
      - EMAIL_LETS_ENCRYPT=me@me.me
      - REDIRECT_HTTP_TO_HTTPS=yes
      - DISABLE_DEFAULT_SERVER=yes
      - PROXY_REAL_IP=yes
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/
      - REVERSE_PROXY_HOST=http://10.0.0.2:8080
      - USE_WHITELIST_IP=yes
      - WHITELIST_IP_LIST=10.88.2.0/24    #whitelist Podman network
      - MAX_CLIENT_SIZE=10G
      - USE_CLIENT_CACHE=yes
      -  ALLOWED_METHODS=GET|POST|HEAD|COPY|DELETE|LOCK|MKCOL|MOVE|PROPFIND|PROPPATCH|PUT|UNLOCK|OPTIONS
      - X_FRAME_OPTIONS=SAMEORIGIN
      - STRICT_TRANSPORT_SECURITY=max-age=63072000;includeSubdomains;
      - USE_GZIP=yes
      - BAD_BEHAVIOR_STATUS_CODE=400|401|403|405|444
      

Edit: the formatting of the compose file is broken here, there is no line break before "ALLOWED_METHODS" ;)

Any clue on this?

Thanks

**Comment by dan-m8t** [comment]
I disabled modsecurity for debugging purposes and without mod security it works just fine. So I guess here's somehow an error inside the owasp rules set?

**Comment by dan-m8t** [comment]
Further investigations:

`bash-5.1$ ls -ld modsec-crs-confs/
drwxr-x---    2 root     root          4096 May 15 12:14 modsec-crs-confs/`

`bash-5.1$ whoami
nginx`

`bash-5.1$ cd modsec-crs-confs/
bash: cd: modsec-crs-confs/: Permission denied`

the nginx user cannot access the custom rules, I set the proper permissions on the host file system and it is working now. 


Maybe you should add proper permissions instructions to the documentation or inside the docker-compose files

**Comment by bunkerity** [comment]
Hello @dan-m8t,

Glad you resolved it. It's already documented in the [quickstart guide](https://bunkerized-nginx.readthedocs.io/en/latest/quickstart_guide.html) and [volumes list](https://bunkerized-nginx.readthedocs.io/en/latest/volumes.html) but it's not clear enough. I've added a comment into the compose examples and an additional check when container starts. Thanks for your suggestion !

**Comment by bunkerity** [comment]
Regarding the `USE_MODSECURITY_CRS` it is set to `yes` by default. You only need to use it if you want to disable the CRS (`USE_MODSECURITY_CRS=no`).
