### ISSUE TITLE
Still issues with crowdsec

### ISSUE THREAD

**Issue by mgiammarco** [bunkerity/bunkerized-nginx#134]
Hello,
I have updated bunkerity following your suggestions.
I have also checked the updated crowdsec example and modified my configuration file to follow yours one.
I still get errors like these:
- Http error 403 while talking to LAPI (http://mycrowdsec:8080/v1/decisions?ip=xxx.xxx.xxx.xxx
- auth api key error: select bouncer: ent: bouncer not found: unable to query

I have one question: in the bash script you create a bouncer called "MyBouncer" but then how do I specify the bouncer name in bunkerity configuration?
Thanks in advance for help.
Mario

**Comment by bunkerity** [comment]
Hello @mgiammarco, 

Can you confirm that you updated the value of the **CROWDSEC_KEY** environment variable (see [here](https://github.com/bunkerity/bunkerized-nginx/blob/master/examples/crowdsec/docker-compose.yml#L25)) with the key given by **cscli bouncers add MyBouncer** ?

**Comment by bunkerity** [comment]
Houston, we have a problem ! It's not directly related to your issue but it's still a problem : since v1.2.5, the log files are not present in /var/log anymore (i.e. : /var/log/access.log is a symlink to /dev/stdout - so Docker can easily manage logs). I need to investigate this, will keep you updated.

**Comment by bunkerity** [comment]
Hello @mgiammarco,

Looks it's fixed on my side. Can you try the current (v1.2.6) version and the up to date [example](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/crowdsec) ?

**Comment by fl0ppy-d1sk** [comment]
CrowdSec is now available as an external plugin. See the [plugin documentation](https://bunkerized-nginx.readthedocs.io/en/latest/plugins.html) and the [dedicated repository](https://github.com/bunkerity/bunkerized-nginx-crowdsec).
