### ISSUE TITLE
[FEATURE]  trusted-types

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerized-nginx#143]
**What's needed and why ?**
As a reminder add trusted-types on header when it will be supported by all browsers.
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types)

**Implementations ideas (optional)**
Add trusted types and endpoint on bunkerized [https://web.dev/trusted-types/](https://web.dev/trusted-types/)

**Comment by fl0ppy-d1sk** [comment]
I reopened by error, didn't remember there was already an issue for that feature...
