### ISSUE TITLE
[BUG] bunkerized-nginx nerver start

### ISSUE THREAD

**Issue by patriarch** [bunkerity/bunkerized-nginx#144]
**Description**
After lanching the docker-compose, the service nerver start.
I tried to change the permissions/ownership of ./letsencrypt with no change at all

**How to reproduce**

>  mywww:
>     image: bunkerity/bunkerized-nginx
>     restart: always
>     ports:
>       - 80:8080
>       - 443:8443
>     volumes:
>       - ./letsencrypt:/etc/letsencrypt
>       - autoconf:/etc/nginx
>     environment:
>       - SERVER_NAME=                                              # must be left blank if you don't want to setup "static" conf
>       - MULTISITE=yes
>       - AUTO_LETS_ENCRYPT=yes
>       - REDIRECT_HTTP_TO_HTTPS=yes
>       - DISABLE_DEFAULT_SERVER=no
>       - USE_CLIENT_CACHE=yes
>       - USE_PROXY_CACHE=yes
>       - USE_GZIP=yes
>       - USE_REVERSE_PROXY=yes
>     labels:
>       - "bunkerized-nginx.AUTOCONF"
> 
>   myautoconf:
>     image: bunkerity/bunkerized-nginx-autoconf
>     restart: always
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock:ro
>       - autoconf:/etc/nginx
>     depends_on:
>       - mywww
>       - *******

**Logs**

> mywww_1            | [*] Catched reload operation
mywww_1            | 2021/06/12 12:57:09 [emerg] 9#9: cannot load certificate "/etc/nginx/default-cert.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/default-cert.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
mywww_1            | nginx: [emerg] cannot load certificate "/etc/nginx/default-cert.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/default-cert.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
mywww_1            | [*] Generated self-signed certificate for default server
mywww_1            | [*] Copying cached user-agents.list ...
mywww_1            | [*] Copying cached referrers.list ...
mywww_1            | [*] Copying cached tor-exit-nodes.list ...
mywww_1            | [*] Downloading proxies list (in background) ...
mywww_1            | [*] Downloading abusers list (in background) ...
mywww_1            | [!] Ignored reload operation because nginx is not running
mywww_1            | [*] bunkerized-nginx stopped
mywww_1            | 2021/06/12 12:57:10 [emerg] 10#10: cannot load certificate "/etc/letsencrypt/live/*******.********.**/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/*******.********.**/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
mywww_1            | nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/*******.********.**/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/*******.********.**/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
mywww_1            | [*] bunkerized-nginx stopped
mywww_1            | 2021/06/12 12:57:12 [emerg] 9#9: cannot load certificate "/etc/letsencrypt/live/*******.********.**/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/*******.********.**/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
mywww_1            | nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/*******.********.**/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/e

**Comment by bunkerity** [comment]
Hello @patriarch, unfortunately, our internal tests didn't catch it. I'm investigating that issue.

**Comment by bunkerity** [comment]
Hey @patriarch,

It should be fixed in the last version. Feel free to open a new issue if needed. Thanks for your report.
