### ISSUE TITLE
Unable to start with Letsencrypt

### ISSUE THREAD

**Issue by ducky710** [bunkerity/bunkerized-nginx#146]
Hello. I'm really excited by this project and want very badly to implement it however I've been trying painstakingly for hours on end now to get started and no matter what I do I simply cannot. I'm getting hit with error after error and unable to generate certificates. The main one being.

> Unable to change owner and uid of webroot directory

Is it possible to override this and run it as root? I just want to get it working.

 I've referenced a previously opened issue on the matter and trying those steps resulted in no change whatsoever.
https://github.com/bunkerity/bunkerized-nginx/issues/105#issuecomment-803613488

My compose is as such.

version: '3'
services:

 nginx:
  image: bunkerity/bunkerized-nginx:latest
  container_name: nginx
  ports:
      - 80:80
      - 443:443
  volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./www:/www
  environment:
      - USE_REVERSE_PROXY=yes
      - SERVER_NAME=plex.domain.tld domain.tld
      - USE_GZIP=yes
      - USE_BROTLI=yes
      - MULTISITE=yes
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - plex.domain.tld_REVERSE_PROXY_URL_1=/
      - plex.domain.tld_REVERSE_PROXY_HOST_1=http://nadeshiko:32400
      - domain.tld_REVERSE_PROXY_URL_2=/
      - domain.tld_REVERSE_PROXY_HOST_2=http://nadeshiko:34447
      - USE_ANTIBOT=cookie
      - DISABLE_DEFAULT_SERVER=yes
      - USE_PROXY_CACHE=yes
  restart: always

Logs

[*] Starting bunkerized-nginx ...

[*] Configuring bunkerized-nginx ...

[*] Successfully started temp nginx

[*] Generation done !

[*] Generated self-signed certificate for default server

[*] Error while executing certbot new : Saving debug log to /var/log/letsencrypt/letsencrypt.log

Plugins selected: Authenticator webroot, Installer None

Account registered.

Requesting a certificate for plex.domain.tld

Performing the following challenges:

http-01 challenge for plex.domain.tld

Using the webroot path /acme-challenge for all unmatched domains.

Unable to change owner and uid of webroot directory

Unable to change owner and uid of webroot directory

Waiting for verification...

Challenge failed for domain plex.domain.tld

http-01 challenge for plex.domain.tld

Cleaning up challenges

Some challenges have failed.

IMPORTANT NOTES:

 - The following errors were reported by the server:

   Domain: plex.domain.tld

   Type:   connection

   Detail: Fetching

   http://plex.domain.tld/.well-known/acme-challenge/7YqDvLaOrIwoCTU_sZ5DRXN7-nfx3-MVDSHUykLAffM:

   Connection refused

   To fix these errors, please make sure that your domain name was

   entered correctly and the DNS A/AAAA record(s) for that domain

   contain(s) the right IP address. Additionally, please check that

   your computer has a publicly routable IP address and that no

   firewalls are preventing the server from communicating with the

   client. If you're using the webroot plugin, you should also verify

   that you are serving files from the webroot path you provided.

[*] Error while executing certbot new : Saving debug log to /var/log/letsencrypt/letsencrypt.log

Plugins selected: Authenticator webroot, Installer None

Requesting a certificate for domain.tld

Performing the following challenges:

http-01 challenge for domain.tld

Using the webroot path /acme-challenge for all unmatched domains.

Unable to change owner and uid of webroot directory

Unable to change owner and uid of webroot directory

Waiting for verification...

Challenge failed for domain domain.tld

http-01 challenge for domain.tld

Cleaning up challenges

Some challenges have failed.

IMPORTANT NOTES:

 - The following errors were reported by the server:

   Domain: domain.tld

   Type:   connection

   Detail: Fetching

   http://domain.tld/.well-known/acme-challenge/DNahC_x32ioV9Z-CXeVq0J4LFhuWJWEhJoE0CDenE3A:

   Connection refused

   To fix these errors, please make sure that your domain name was

   entered correctly and the DNS A/AAAA record(s) for that domain

   contain(s) the right IP address. Additionally, please check that

   your computer has a publicly routable IP address and that no

   firewalls are preventing the server from communicating with the

   client. If you're using the webroot plugin, you should also verify

   that you are serving files from the webroot path you provided.

2021/06/22 21:59:25 [notice] 100#100: signal process started

[*] Running nginx ...

[*] Downloading bad user-agent list (in background) ...

[*] Downloading bad referrer list (in background) ...

[*] Downloading tor exit nodes list (in background) ...

[*] Downloading proxies list (in background) ...

[*] Downloading abusers list (in background) ...

[2021-06-22 21:59:25] [BLACKLIST] TOR exit node list updated (1078 entries)

[2021-06-22 21:59:25] [BLACKLIST] referrers list updated (7064 entries)

[2021-06-22 21:59:25] [BLACKLIST] user-agent list updated (1713 entries)

2021/06/22 21:59:25 [emerg] 101#101: cannot load certificate "/etc/letsencrypt/live/plex.domain.tld/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/plex.domain.tld/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/plex.domain.tld/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/plex.domain.tld/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

**Comment by ducky710** [comment]
On second thought, the issue might not only be permissions but also the fact that i'm using cloudflare.

**Comment by ducky710** [comment]
Oh my god. I was using the wrong ports the whole time. I didn't realize it was supposed to be 8080 and 8443. 🤦‍♂️
Theres 16 hours of my life i'll never get back. I'm super close to having this working now. I had switched to an old image "1.2.1" and that let me get one certificate successfully! Back on the latest i'm still having permission issues, but its almost working now.
![tumblr_cbce909fef4c202399194dde6dbc0534_3174bbf8_500](https://user-images.githubusercontent.com/63337938/123036053-6a8dfc80-d3ba-11eb-9b82-c96048a17aa7.jpg)

**Comment by ducky710** [comment]
Alright problem resolved. It was the ports and running the commands previously specific in comment #105 did it.

**Comment by bunkerity** [comment]
Glad you resolved it. That meme is awesome by the way !
