### ISSUE TITLE
[FEATURE] Inject custom Javascript in Environment variable

### ISSUE THREAD

**Issue by ducky710** [bunkerity/bunkerized-nginx#149]
The ability to easily inject custom .js scripts into your individual hosts as an environment variable would be immensely useful for those who use traffic tracking scripts from services like Shynet and have lots of sites. 
https://github.com/milesmcc/shynet

Example of Shynet's script and instructions

```
Place the following snippet at the end of the <body> tag on any page you'd like to track.
<noscript>
    <img src="https://stats.domain.tld/ingress/3d1b9899-9331-4856-a7a3-35c7cb27121f/pixel.gif">
</noscript>
<script defer src="https://stats.domain.tld/ingress/3d1b9899-9331-4856-a7a3-35c7cb27121f/script.js"></script>
```

Something like this

- sub.domain.tld_REVERSE_PROXY_URL_1=/
- sub.domain.tld_REVERSE_PROXY_HOST_1=http://local:8080
- sub.domain.tld_INJECT_JS_BODY=https://stats.domain.tld/ingress/3d1b9899-9331-4856-a7a3-35c7cb27121f/script.js

**Comment by fl0ppy-d1sk** [comment]
Hey @ducky710,

I like the idea and understand the need. I'm adding it to the TODO list.

**Comment by ducky710** [comment]
Appreciate it! Looking forward to it being included eventually :D Cheers~

**Comment by fl0ppy-d1sk** [comment]
Hello @ducky710,

The new [v1.3.0 release](https://github.com/bunkerity/bunkerized-nginx/releases/tag/v1.3.0) introduces the `INJECT_BODY` environment variable (see the [environment variables list](https://bunkerized-nginx.readthedocs.io/en/latest/environment_variables.html) for more information). Thanks again for your suggestion.
