### ISSUE TITLE
Releases & Tags

### ISSUE THREAD

**Issue by FacundoAcevedo** [bunkerity/bunkerized-nginx#15]
It's very useful to use tags in docker-hub and Releases here in github so we can pin a specific version to avoid surprises when using latest :P

**Comment by bunkerity** [comment]
Hello @FacundoAcevedo, we've integrated your suggestion. To avoid (bad) surprises you can reference the docker or git tag of your choice (example for the current version : [docker](https://hub.docker.com/layers/bunkerity/bunkerized-nginx/1.0.0/images/sha256-665590e045ed5e8996003445b09c83953e3a1d31f44c926f78516f5cf8c7103f?context=explore) and [git](https://github.com/bunkerity/bunkerized-nginx/releases/tag/v1.0.0)).
