### ISSUE TITLE
301 redirect if there's no trailing slash

### ISSUE THREAD

**Issue by pilasguru** [bunkerity/bunkerized-nginx#151]
**Description**
I have a file `/about/index.html` at server root filesystem, but when I try to GET it with
```
curl http://localhost/about
```
returns:
```
HTTP/1.1 301 Moved Permanently
Location: http://localhost/about/

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
and logs:
```
"GET /about HTTP/1.1" 301 162 " 
```
and I understant that the configured directive `try_files $uri $uri/ =404;` would search the folder with `/` and try to serve the `index index.html index.php;` 

Do you know other way to avoid 301 redirect and enable nginx to serve the index.html file adding the last `/` and avoid 301 redirect.

In have found these references, but replies do not help.
https://stackoverflow.com/questions/15555428/nginx-causes-301-redirect-if-theres-no-trailing-slash
https://serverfault.com/questions/759762/how-to-stop-nginx-301-auto-redirect-when-trailing-slash-is-not-in-uri/812461#812461

**Comment by fl0ppy-d1sk** [comment]
Hello @pilasguru,

What about using the `rewrite` directive ? Just quickly tested it and there is no 301 on my side :
```conf
rewrite ^/about$ /about/ last;
```

You can include custom configurations at server context by mouting .conf files into the /server-confs volume (more info [here](https://bunkerized-nginx.readthedocs.io/en/latest/volumes.html#custom-nginx-configurations)).

**Comment by pilasguru** [comment]
Thank you @fl0ppy-d1sk. The solution I use is:
```
   rewrite ^([^.]*[^/])$ $1/ last;
```
as first line together our all other custom locations into `/server-confs` conf file.
