### ISSUE TITLE
[FEATURE] Make worker_processes parameter configurable

### ISSUE THREAD

**Issue by jakearlen879** [bunkerity/bunkerized-nginx#158]
**What's needed and why?**

Is it possible for the `worker_processes` parameter to be configurable with an environment variable? It'll be useful for performance tuning.

https://github.com/bunkerity/bunkerized-nginx/blob/master/confs/global/nginx.conf#L20

**Implementations ideas**

_confs/global/nginx.conf:_
`worker_processes {{ WORKER_PROCESSES }};`

_confs/global/nginx-temp.conf:_
`worker_processes auto;`

\+ documentation

**Comment by fl0ppy-d1sk** [comment]
Hey @jakearlen879,

Nice suggestion, it won't hurt to add the `WORKER_PROCESSES` with a default value of `auto` in the next release.

**Comment by fl0ppy-d1sk** [comment]
Hello @jakearlen879,

The `WORKER_PROCESSES` is now available in the [v1.3.0 release](https://github.com/bunkerity/bunkerized-nginx/releases/tag/v1.3.0). See the [list of environment variables](https://bunkerized-nginx.readthedocs.io/en/latest/environment_variables.html) for more information.
