### ISSUE TITLE
How do i use this on repl.it

### ISSUE THREAD

**Issue by vackyton** [bunkerity/bunkerized-nginx#159]
I don't know how i can add this on my repl.it it cause i attacked my site once to test it and it is terrible so i was wondering how to do it on repl.it?

**Comment by fl0ppy-d1sk** [comment]
Hello @vackyton,

I might be wrong but it looks like you can't host your own instance of replt.it ?

**Comment by vackyton** [comment]
oh

**Comment by vackyton** [comment]
https://holyunblockerpublic-1.vackyton.repl.co/

**Comment by vackyton** [comment]
it is the sit

**Comment by vackyton** [comment]
*that is the site i want to put it*

**Comment by fl0ppy-d1sk** [comment]
Usualy you need to have access to the web service. But maybe you can try to put bunkerized-nginx as a reverse proxy in front of that app ? See the [doc](https://bunkerized-nginx.readthedocs.io/en/latest/quickstart_guide.html#as-a-reverse-proxy) and a [compose example](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/reverse-proxy-singlesite). You will surely need to override the forwarded Host header by using the `REVERSE_PROXY_HEADERS` environment variable.

**Comment by vackyton** [comment]
ok btw i don't know too much websites xD

**Comment by fl0ppy-d1sk** [comment]
Closing this because there is no information. Don't hesitate to open a new issue if you have a specific problem.

**Comment by vackyton** [comment]
k
