### ISSUE TITLE
[BUG] Expired SSL certificate for demo site

### ISSUE THREAD

**Issue by l4rm4nd** [bunkerity/bunkerized-nginx#161]
**Description**
Browsing the demo site leads to an SSL certificate error, since the cert is expired.

**How to reproduce**
Just browse [https://demo-nginx.bunkerity.com/](https://demo-nginx.bunkerity.com).

![image](https://user-images.githubusercontent.com/21357789/126483618-31511b76-fd24-406a-85bc-08894c9cdda9.png)

![image](https://user-images.githubusercontent.com/21357789/126483715-49b8de20-7424-42c0-936d-a5aaa5c74a1b.png)

**Comment by fl0ppy-d1sk** [comment]
Hello @l4rm4nd,

Thanks for your report, I will fix it soon.

**Comment by fl0ppy-d1sk** [comment]
Should be fixed, thanks again @l4rm4nd.
