### ISSUE TITLE
[FEATURE] Add support folder names with dots

### ISSUE THREAD

**Issue by derdek** [bunkerity/bunkerized-nginx#165]
**What's needed and why ?**
I use for my projects folders with dots, for example:
- project1.example.com
- project2.example.com
- example.com
it's very confortable

**Implementations ideas (optional)**
I propose add dot to regex
Ignoring example.com_REMOTE_PHP_PATH=/usr/share/nginx/example.com (doesn't match regex : `^/([A-Za-z0-9\-\.]/?)*$)`
Ignoring project1.example.com_REMOTE_PHP_PATH=/usr/share/nginx/project1.example.com (doesn't match regex : `^/([A-Za-z0-9\-\.]/?)*$)
`

**Comment by fl0ppy-d1sk** [comment]
It should be fixed in the new v1.2.8 version.

**Comment by fl0ppy-d1sk** [comment]
Closing this as it should be resolved.
