### ISSUE TITLE
[FEATURE] ngx_http_limit_req_module patch that support rating per hour/day/week

### ISSUE THREAD

**Issue by hoaivan** [bunkerity/bunkerized-nginx#167]
**What's needed and why ?**
Nginx only support rate limit per second or minutes. It would be better  to have per hour/day/week 

**Implementations ideas (optional)**
This is a ngx_http_limit_req_module patch that support. Pls integrate this patch into bunkerized-nginx:   
https://www.getpagespeed.com/nginx-mod-a-better-faster-nginx-build

**Comment by fl0ppy-d1sk** [comment]
Hello @hoaivan,

I might be wrong but that patch isn't Open Source. They charge 10$ for getting access to the pre-built packages. Unless we have an Open Source alternative, we will need to do it from scratch.

**Comment by hoaivan** [comment]
You're right. Let me close the issue.
