### ISSUE TITLE
New feature: Certbot dry-run

### ISSUE THREAD

**Issue by bognolo** [bunkerity/bunkerized-nginx#168]
**What's needed and why ?**
To avoid running into letsencrypt rate limits when configuring bunkerized-nginx for the first time, it would be useful to have the option to use certbot's `--dry-run` option to generate certificates against letsencrypt's staging environment.

Adding a boolean environment variable to add the switch to the certbot call should be sufficient.

Thanks!

**Comment by fl0ppy-d1sk** [comment]
Hello @bognolo,

I'm not sure if `--dry-run` will write a test certificate to the disk (from the [doc](https://certbot.eff.org/docs/using.html)) : 
```
--dry-run         Test "renew" or "certonly" without saving any certificates to disk
```

But looks like `--staging` will do the trick : 
```
--test-cert, --staging
                        Use the staging server to obtain or revoke test
                        (invalid) certificates; equivalent to --server
                        https://acme-staging-v02.api.letsencrypt.org/directory
```

**Comment by bognolo** [comment]
Thank you fl0ppy-d1sk,
you are right, I must have got confused there. Hopefully we will get the functionality soon ;-)

**Comment by fl0ppy-d1sk** [comment]
Hello @bognolo

The `USE_LETS_ENCRYPT_STAGING` environment variable has been added to the [v1.3.0 release](https://github.com/bunkerity/bunkerized-nginx/releases/tag/v1.3.0). More info [here](https://bunkerized-nginx.readthedocs.io/en/latest/environment_variables.html?highlight=staging#let-s-encrypt).
