### ISSUE TITLE
[FEATURE] Add custom headers

### ISSUE THREAD

**Issue by Myzel394** [bunkerity/bunkerized-nginx#171]
**What's needed and why ?**
Some people don't want their instances to be visible on Google, Duckduckgo, etc. You can disable crawling from most search engines using the `X-Robots-Tag: noindex` tag.

**Implementations ideas (optional)**
Add the option to add the `X-Robots-Tag` header (or provide a way to add custom headers in general, that would be even better :P)

**Comment by fl0ppy-d1sk** [comment]
Hey @Myzel394,

Thanks for your suggestion. I agree, a generic feature to add custom headers would be better ! Let's add it to the TODO list.

**Comment by fl0ppy-d1sk** [comment]
Hello @Myzel394,

You can now use `CUSTOM_HEADER_1`, `CUSTOM_HEADER_2`, `CUSTOM_HEADER_3`, ... environment variables with the last release. More info [here](https://bunkerized-nginx.readthedocs.io/en/latest/environment_variables.html?highlight=CUSTOM_HEADER#misc).

Feel free to open a new issue if needed.
