### ISSUE TITLE
[FEATURE] Ability to set proxy_buffering without needing an entire serverconf.

### ISSUE THREAD

**Issue by wegotshrimp** [bunkerity/bunkerized-nginx#178]
**What's needed and why ?**
The ability to turn off proxy buffering is recommended for some applications like Jellyfin when performing live streaming to preserve proxy resources, so I would like to be able to set that similar to REVERSE_PROXY_WS and REVERSE_PROXY_HEADERS.

**Implementations ideas (optional)**
Perhaps similar to the function of REVERSE_PROXY_HEADERS, a REVERSE_PROXY_OPTIONS env variable that is delimited by semi-colors and adds actions to the reverse_proxy.conf if the list is longer than 1. Rather than looping through and adding a proxy_set_header <option>, make the env variable require the full syntax of <option> <value> when separating them and iterating over the list as just options. Maybe that goes outside the scope of just being able to add more proxy options though (perhaps loop over with proxy_<option> <value>; in reverse_proxy.conf?).

**Comment by fl0ppy-d1sk** [comment]
Hello @wegotshrimp,

The `REVERSE_PROXY_BUFFERING` variable is now implemented into the last v1.3.1 release. More info [here](https://bunkerized-nginx.readthedocs.io/en/latest/environment_variables.html?highlight=REVERSE_PROXY_BUFFERING#reverse-proxy).

Feel free to open a new issue if needed.
