### ISSUE TITLE
[FEATURE] Add crowdsec

### ISSUE THREAD

**Issue by markham89** [bunkerity/bunkerized-nginx#23]
CrowdSec is a security automation engine, using both local IP behavior detection & our community-driven IP reputation database.

[https://crowdsec.net/](https://crowdsec.net/)

**Comment by bunkerity** [comment]
Hello, thanks for your suggestion. Basic CrowdSec integration has been added in version [1.1.2](https://github.com/bunkerity/bunkerized-nginx/releases/tag/v1.1.2). Please note that you need to explicitly turn it on by setting the environment variable **USE_CROWDSEC** to **yes** (more info [here](https://github.com/bunkerity/bunkerized-nginx#crowdsec)).
