### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Raffael93** [bunkerity/bunkerized-nginx#242]
Certbot can't generate logs and certificate
![image](https://user-images.githubusercontent.com/39736925/164424406-ae9c7dc0-ec44-4ae5-83b5-7872d7a3b143.png)

**How to reproduce**
![followed](https://user-images.githubusercontent.com/39736925/164424710-e19d1bc2-fe50-4660-ab4c-66a072476528.PNG)

**Comment by cocoonkid** [comment]
In which dir are you executing this?  Can you show us the precise command you are executing and the PWD and it's permissions? And as which user?

![Screeshot 2022-04-22 at 08 14 28@2x](https://user-images.githubusercontent.com/43231640/164614571-f763dece-f10c-4bb5-a14c-45155da7c06a.jpg)

**Comment by cocoonkid** [comment]
and please add "Certbot can't generate logs and certificate" to the title . Just [BUG] is not helpful :-)
