### ISSUE TITLE
proxies.sh cpu usage

### ISSUE THREAD

**Issue by e-minguez** [bunkerity/bunkerized-nginx#25]
It seems overkill that for every restart the proxies.sh downloads and process the whole file... it takes a while and it consumes a lot of CPU. I guess it would be better to cache it somewhere in a volume or something else to speed things up.

**Comment by bunkerity** [comment]
Hello @e-minguez, the last [1.2.0](https://github.com/bunkerity/bunkerized-nginx/releases/tag/v1.2.0) version now implements a caching system. You can activate it by mounting a volume to the /cache folder. More info [here](https://github.com/bunkerity/bunkerized-nginx#cache-data).
