### ISSUE TITLE
X-Frame-Options requires "SAMEORIGIN" for nextcloud for an A+ rating

### ISSUE THREAD

**Issue by e-minguez** [bunkerity/bunkerized-nginx#26]
https://docs.nextcloud.com/server/20/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx & https://help.nextcloud.com/t/security-warning-on-x-frame-options-http-header-is-not-set-to-sameorigin/37118

So in https://github.com/bunkerity/bunkerized-nginx/blob/95752ff0c41a3806772e685c0effc2f9ee15e017/examples/nextcloud/docker-compose.yml#L28 I needed to add `X_FRAME_OPTIONS=SAMEORIGIN` in order to get A+ in https://scan.nextcloud.com/

**Comment by bunkerity** [comment]
Thanks for your report. Fixed in [1.1.2](https://github.com/bunkerity/bunkerized-nginx/releases/tag/v1.1.2).
