### ISSUE TITLE
[Enhancement] Missing nginx module : brotli, http3

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerized-nginx#30]
Hi,

Could it be possible to add bortli compresssion module and http3 module for nginx ? :)
https://dev.to/koddr/how-to-install-brotli-module-for-nginx-on-ubuntu-20-04-2ocp
https://medium.com/faun/implementing-http3-quic-nginx-99094d3e39f

Thanks a lot!

**Comment by bunkerity** [comment]
Hello @thelittlefireman, thanks for your suggestion.

I think it's a good idea to support brotli especially if we can turn it on or off easily. It will be integrated, with gzip support too, in the next release. The only problem is that we need to find a way to "easily" mitigate the [BREACH attack](http://breachattack.com) when compression is enabled. Regarding HTTP3 support, IMO, we should wait until it's integrated into the stable version.

**Comment by bunkerity** [comment]
Hello @thelittlefireman, the new [1.2.0](https://github.com/bunkerity/bunkerized-nginx/releases/tag/v1.2.0) version now integrates brotli and gzip support. You can activate/customize it through environment variables. More info [here](https://github.com/bunkerity/bunkerized-nginx#compression).

Regarding HTTP3, do not hesitate to reopen a new issue when it's available as a dynamic module and/or integrated into the stable nginx.
