### ISSUE TITLE
DNS issues with reverse_proxy

### ISSUE THREAD

**Issue by BigNerd95** [bunkerity/bunkerized-nginx#33]
Using reverse_proxy, error.log is full of `lua udp socket read timed out` even with upstream server with IP and no dns name.
Any idea?

**Comment by BigNerd95** [comment]
Solved with `USE_DNSBL=no`
I leave this issue open so maybe you can fix DNSBL
I think the problem is with the default DNS_RESOLVERS
resty.dns.resolver tries to resolve ip of reverse proxy, and if 127.0.0.11 doesn't contain a match, it will hang and then timeout, blocking the request for 10 seconds (5 timeouts of 2 seconds each one)

**Comment by bunkerity** [comment]
Hello @BigNerd95, can you provide more information like context, configs and logs please ? 127.0.0.11 is the internal Docker DNS resolver, I don't know if it's the culprit or maybe it's one of the DNSBL defined in the `DNSBL_LIST` environment variable ?

**Comment by BigNerd95** [comment]
docker-compose.yml
```
version: '3.8'

services:
    web:
        image: bunkerity/bunkerized-nginx
        restart: unless-stopped
        ports:
            - 80:8080
            - 80443:8443
        volumes: 
            - ./www:/www
            - ./certs:/etc/letsencrypt
            - ./confs:/server-confs
        environment:
            - SERVE_FILES=no
            - DISABLE_DEFAULT_SERVER=yes
            - SERVER_NAME=mydomain.com
            - AUTO_LETS_ENCRYPT=yes
            - LISTEN_HTTP=no
            - REDIRECT_HTTP_TO_HTTPS=no
```

server.conf
```
absolute_redirect off;

proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

location /url/ {
        proxy_pass http://x.x.x.x:1234/;
        proxy_buffering off;
}

```

/var/log/error.log
```
2020/12/19 11:38:04 [error] 1764#1764: *537 lua udp socket read timed out, client: x.x.x.x, server: mydomain.com, request: "GET /url/asd HTTP/2.0", host: "mydomain.com:80443"
2020/12/19 11:38:06 [error] 1764#1764: *537 lua udp socket read timed out, client: x.x.x.x, server: mydomain.com, request: "GET /url/asd HTTP/2.0", host: "mydomain.com:80443"
2020/12/19 11:38:06 [error] 1764#1764: *537 lua entry thread aborted: runtime error: /usr/local/lib/lua/dns.lua:13: attempt to index local 'answers' (a nil value)#012stack traceback:#012coroutine 0:#012#011/usr/local/lib/lua/dns.lua: in function 'get_reverse'#012#011/usr/local/lib/lua/blacklist.lua:36: in function 'check_reverse'#012#011access_by_lua(main-lua.conf:144):70: in main chunk, client: x.x.x.x, server: mydomain.com, request: "GET /url/asd HTTP/2.0", host: "mydomain.com:80443"
```

**Comment by bunkerity** [comment]
Hello @BigNerd95,

Since new versions, it should concerns only the first request made by an IP address. The other requests won't be affected because the result is already cached. You can try an up-to-date version of bunkerized-nginx and reopen a new issue if needed.
