### ISSUE TITLE
Missing Permissions-Policy security header

### ISSUE THREAD

**Issue by jakearlen879** [bunkerity/bunkerized-nginx#34]
_securityheaders.com_ reports missing _Permissions-Policy_ security header:

https://securityheaders.com/?q=https%3A%2F%2Fdemo-nginx.bunkerity.com&followRedirects=on

![image](https://user-images.githubusercontent.com/74742569/99730465-c9a23080-2abc-11eb-988e-60643a2d4cb6.png)

**Comment by bunkerity** [comment]
Hello @jakearlen879, Permissions-Policy header has been added into the last [1.2.0](https://github.com/bunkerity/bunkerized-nginx/releases/tag/v1.2.0) version. More info [here](https://github.com/bunkerity/bunkerized-nginx#security-headers).
