### ISSUE TITLE
web ui to read/edit configurations

### ISSUE THREAD

**Issue by lucmichalski** [bunkerity/bunkerized-nginx#37]
Hi @bunkerity ,

Hope you are all well !

I think that it would a really useful extra docker images for Nginx to add this project https://github.com/jc21/nginx-proxy-manager.

What do you think ? It would be interesting to have a secured dashboard for any Nginx service.

Thanks for any inputs or insights on that.

Cheers,
X

**Comment by bunkerity** [comment]
Hello @lucmichalski, thanks for your suggestion.

Looks like interesting. It might be useful to add new website or edit existing websites configuration on-the-fly easily with a web UI. For now, bunkerized-nginx heavily uses environment variables to configure everything and the drawback is that we need to recreate a new container each time we edit the configuration. We plan to integrate something with labels (like [Traefik](https://doc.traefik.io/traefik/providers/docker/) does) to make it more dynamic. I think it's the top priority right now. Once we can generate configuration on-the-fly, it should be "easier" to add a web UI on top of that.

Regarding the implementation, I can't say for now if we should fork [jc21/nginx-proxy-manager](https://github.com/jc21/nginx-proxy-manager), fork another project or even start something from scratch. Let's first stick with the "dynamic configuration" part.

I keep this open and will post related updates. 👍

**Comment by lucmichalski** [comment]
Awesome, let me know.

Ps. If you wanna DM and not polluting this thread, my twitter handle is https://twitter.com/lucmichalski

**Comment by lucmichalski** [comment]
Hi @bunkerity ,

Hope you are all well !

I found another nginx web panel written in python: https://github.com/schenkd/nginx-ui

What do you think about this one ?

Cheers,
Luc Michalski

**Comment by bunkerity** [comment]
#60

**Comment by bunkerity** [comment]
Hey @lucmichalski,

A web UI has been released in the v1.2.2 version. More info [here](https://github.com/bunkerity/bunkerized-nginx#web-ui) and a full example is [here](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/web-ui). Feel free to test it and give feedbacks :).

Please note that I've opened a matrix chat [#bunkerized-nginx:matrix.org](https://matrix.to/#/#bunkerized-nginx:matrix.org) if you wish to discuss about the project.
