### ISSUE TITLE
seems fail2ban in multisite mode have a bug

### ISSUE THREAD

**Issue by zherdev-artem** [bunkerity/bunkerized-nginx#41]
Hi, first of all, thank you for the awesome project and new releases (the last one with reverse proxy multisite is cool).

But, seems fail2ban save banned ips to /etc/nginx/fail2ban-ip.conf and it not applying anywhere. If I right understand it will work if banned IP will set to /etc/nginx/ {server_name }/fail2ban-ip.conf in the site folder.

**Comment by zherdev-artem** [comment]
Sorry, I just need to carefully read docs at all.

**Comment by bunkerity** [comment]
Hello @zherdev-artem, I think you're right. We need to include /etc/nginx/fail2ban-ip.conf and not /etc/nginx/{server_name}/fail2ban-ip.conf.

**Comment by bunkerity** [comment]
Hello @zherdev-artem, 

Fix has been integrated into the [v1.2.1](https://github.com/bunkerity/bunkerized-nginx/releases/tag/v1.2.1). Thanks !
