### ISSUE TITLE
Owasp CRS - TX:OUTBOUND_ANOMALY_SCORE - Prestashop

### ISSUE THREAD

**Issue by lucmichalski** [bunkerity/bunkerized-nginx#42]
Hi @bunkerity ,

Hope you are still all well :-) !

I am trying to create a dockerized stack with all bunkerity services for a secured prestashop deploy. 
It is almost done but I have some issues that I do not understand fully or maybe it is inherent to Prestashop's coding flaws ^^.

Randomly, I have this error message by  ModSecurity when browsing the frontend or the backend.

```txt
nginx-bunkerized | 2020/11/30 05:53:03 
[error] 21820#21820: *1 
[client 78.244.147.20] ModSecurity: Access denied with code 403 (phase 4). Matched "Operator `Ge' with parameter `4' against variable `TX:OUTBOUND_ANOMALY_SCORE' (Value: `4' ) 
[file "/etc/nginx/owasp-crs/RESPONSE-959-BLOCKING-EVALUATION.conf"] 
[line "68"] 
[id "959100"] 
[rev ""] 
[msg "Outbound Anomaly Score Exceeded (Total Score: 4)"] 
[data ""] 
[severity "0"] 
[ver "OWASP_CRS/3.3.0"] 
[maturity "0"] 
[accuracy "0"] 
[tag "anomaly-evaluation"] 
[hostname "172.18.0.11"] 
[uri "/your-admin/index.php/common/notifications"] 
[unique_id "160671558369.757397"] 
[ref ""] while sending to client, client: X.X.X.X, server: your-domain.com, request: "GET /your-admin/index.php/common/notifications?_token=Zin_r3vpLV3aTIWgrEn6r7J58XLNt8fIn-_3jm0YGpo&rand=1606715538307 HTTP/2.0", upstream: "fastcgi://172.18.0.10:9000", host: "your-domain.com"
```
Ps. I changed de IP, domain and url values for generic values on purpose.

Do you know why ? Is there a way to tweak the TX:OUTBOUND_ANOMALY_SCORE ?

Thanks for any insights or inputs on that issue.

Cheers,
Luc

**Comment by bunkerity** [comment]
Hello @lucmichalski, to get more info see the /var/log/nginx/modsec_audit.log file inside the container. You can update rules by adding .conf files inside the /modsec-confs folder (more info [here](https://github.com/bunkerity/bunkerized-nginx#modsecurity) and a passbolt example [here](https://github.com/bunkerity/bunkerized-nginx/blob/master/examples/passbolt/modsec-confs/passbolt.conf)). I think tweaking the default CRS config is not supported ATM (or maybe you can override the settings by adding a file in the /modsec-confs folder ? didn't test it). I will look deeper into it when I have time.

**Comment by lucmichalski** [comment]
Awesome :-) 

And thanks so much for the reply :-)

I ll try to implement bunkerized-php with prestashop today, keep you updated too.

Have a nice day !
