### ISSUE TITLE
Add socket capability to reverse proxy

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerized-nginx#44]
Hi,
Could it be possible to configure reverse proxy as a websocket ?

```
proxy_set_header        Upgrade           $http_upgrade;
proxy_set_header        Connection        "upgrade";
```

I know it could be done by a custom nginx conf in /server-confs but an env variable would be great `app.site_REVERSE_PROXY_WS=yes`
Thanks for all :)

**Comment by bunkerity** [comment]
Hello @thelittlefireman,

We have added the `REVERSE_PROXY_WS` environment variable into the [v1.2.1](https://github.com/bunkerity/bunkerized-nginx/releases/tag/v1.2.1) version. Thanks for your suggestion.

**Comment by thelittlefireman** [comment]
Huuge thanks again, that's perfect ! 🙂👍

**Comment by e-minguez** [comment]
Can websocket be enabled only in specific sites if using multisite reverseproxy? I've used the `custom.conf` to run home-assistant but it would be nice to get rid of it if supported.
Thanks.

**Comment by bunkerity** [comment]
@e-minguez : yes it should work in MULTISITE mode.
