### ISSUE TITLE
Add modsecurity detect only capability

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerized-nginx#45]
Hi,
Will we are testing a new config we should be able to configure mod security engine in `SecRuleEngine DetectionOnly` mod
to not be ban directly by fail2ban due to many false positive.

Thanks for all :)

**Comment by bunkerity** [comment]
Hello @thelittlefireman,

You can set your own ModSecurity config by mounting .conf files inside the /modsec-confs folder (more info [here](https://github.com/bunkerity/bunkerized-nginx#modsecurity)).

Content of my-modsec-confs/custom.conf : 
```
SecRuleEngine DetectionOnly
```

Mounting the volume : 
```
docker run ... -v /path/to/my-modsec-confs:/modsec-confs ... bunkerity/bunkerized-nginx
```

Please tell me if that does the trick.

**Comment by thelittlefireman** [comment]
Working. We can close this issue.
