### ISSUE TITLE
Multisite basic auth

### ISSUE THREAD

**Issue by xn3cr0nx** [bunkerity/bunkerized-nginx#48]
Hey guys, I am facing an issue setting up basic auth for multisite. Checking inside the container I can see an `.htpasswd` file is created for each server name in the related folder. Navigating to any of the server names and inserting correct credentials I get 403 forbidden and from logs I can see the error saying `.htpasswd not found` because it looks for the file in `/etc/nginx/.htpasswd`, while the file is in `/etc/nginx/server_name/.htpasswd`. Have you already face or are you aware of this?

**Comment by bunkerity** [comment]
This should be fixed in the new v1.2.2 version. Please note that I've opened a matrix chat [#bunkerized-nginx:matrix.org](https://matrix.to/#/#bunkerized-nginx:matrix.org) if you wish to discuss about the project.
