### ISSUE TITLE
error in documentation

### ISSUE THREAD

**Issue by AliaksandrLiavitski** [bunkerity/bunkerized-nginx#50]
you have an error in the multisite section. the documentation says to use the following settings:

          -e app1.domain.com_PROXY_URL=/ \
           -e app1.domain.com_PROXY_HOST=http://myapp1:8000 \
           -e app2.domain.com_PROXY_URL=/\
           -e app2.domain.com_PROXY_HOST=http://myapp2:8000

but it doesn't work.
I was only able to set it up after I changed these lines to the following:

           -e app1.domain.com_PROXY_URL=/ \
           -e app1.domain.com_REVERSE_PROXY_HOST=http://myapp1:8000 \
           -e app2.domain.com_PROXY_URL=/\
           -e app2.domain.com_REVERSE_PROXY_HOST=http://myapp2:8000

Please check this and correct it.

**Comment by bunkerity** [comment]
Fixed in the new v1.2.2 version.

Please note that I've opened a matrix chat [#bunkerized-nginx:matrix.org](https://matrix.to/#/#bunkerized-nginx:matrix.org) if you wish to discuss about the project.
