### ISSUE TITLE
nginx does'nt run (map-user-agent.conf fail)

### ISSUE THREAD

**Issue by markham89** [bunkerity/bunkerized-nginx#55]
Hi,

nginx doesn't run when i lauch docker because :
nginx: [emerg] unexpected "}" in /etc/nginx/map-user-agent.conf:4

**Comment by thelittlefireman** [comment]
What's your docker configuration and what's in your server-confs folder ?

**Comment by markham89** [comment]
version: '3'
services:
  myreverse:
    image: 'bunkerity/bunkerized-nginx:latest'
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './certificats:/etc/certificats'
      - './server-confs:/server-confs'
    environment:
      - SERVER_NAME=website1.fr website2.fr
      - SERVE_FILES=no
      - DISABLE_DEFAULT_SERVER=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - AUTO_LETS_ENCRYPT=no
      - USE_CROWDSEC=yes
      - USE_CUSTOM_HTTPS=yes
      - CUSTOM_HTTPS_CERT=/etc/certificats/mycert.crt
      - CUSTOM_HTTPS_KEY=/etc/certificats/mycert.key

**Comment by bunkerity** [comment]
This should be fixed in the v1.2.2 version.

Please note that I've opened a matrix chat [#bunkerized-nginx:matrix.org](https://matrix.to/#/#bunkerized-nginx:matrix.org) if you wish to discuss about the project.
