### ISSUE TITLE
please update crowdsec (v1.0.2 is fully compatible alpine) 

### ISSUE THREAD

**Issue by markham89** [bunkerity/bunkerized-nginx#56]
Hi,

Please update crowdsec (v1.0.2 is fully compatible alpine) 
Thx,

**Comment by thelittlefireman** [comment]
Maybe we also need to switch to the new nginx-bouncer https://github.com/crowdsecurity/cs-nginx-bouncer

**Comment by bunkerity** [comment]
Hey @markham89,

The new v1.2.2 version is now fully compatible with CrowdSec 1.X. More info [here](https://github.com/bunkerity/bunkerized-nginx#crowdsec) and a full example [here](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/crowdsec).
