### ISSUE TITLE
Add VTS module 

### ISSUE THREAD

**Issue by ichasco** [bunkerity/bunkerized-nginx#58]
Hi!

Could you add VTS module and add in the entrypoint a section to expose the metrics enabling them with a variable?

Thanks!!

**Comment by bunkerity** [comment]
Hello @ichasco,

Do you know an active VTS module we can use ? Looks like [hnlq715/nginx-vts-exporter](https://github.com/hnlq715/nginx-vts-exporter) and [vozlt/nginx-module-vts](https://github.com/vozlt/nginx-module-vts) are no longer maintained.

**Comment by ichasco** [comment]
Hi, the issue can be closed, finally I used a own nginx with prometheus lua lib:

https://github.com/knyar/nginx-lua-prometheus

Thanks!

**Comment by bunkerity** [comment]
Hi @ichasco,

Thanks for that project might be usefull to integrate it into bunkerized-nginx.

**Comment by ichasco** [comment]
@bunkerity if you want to take a look, here is my repo: https://github.com/ichasco/Nginx.

It includes the prometheus lib.
