### ISSUE TITLE
Use docker-socket-proxy for the web UI

### ISSUE THREAD

**Issue by ptr1337** [bunkerity/bunkerized-nginx#60]
I just thought that the "docker-socket-proxy" could help out there. 

Traefik and so on using also the docker.socket. 

Here ill provide you nice example. 

https://github.com/ptTrR/traefik2/blob/master/ymlfiles/docker-socket-proxy.yml

**Comment by bunkerity** [comment]
Hello @ptTrR,

Thanks for your suggestion. We already managed this security issue by creating a dedicated container which is not facing internet and not opening any ports. This change is present in the [dev branch](https://github.com/bunkerity/bunkerized-nginx/tree/dev/autoconf) and will be available with the next release.

But this "docker-socket-proxy" might be usefull for the upcoming [web UI](https://github.com/bunkerity/bunkerized-nginx/tree/dev/ui) feature. Let's keep this issue open as a reminder.

**Comment by ptTrR** [comment]
Alright, but thats the most used solution this security problem. 
Just was an idea. Looking forward to your new release!

**Comment by bunkerity** [comment]
Hello @ptr1337,

I've added an example on how to use the docker-socket-proxy with web UI in the [security tuning section](https://bunkerized-nginx.readthedocs.io/en/latest/security_tuning.html#web-ui) of the documentation. Thanks for your report.

**Comment by ptr1337** [comment]
Hey, 

sorry for the late answer. 
I will test this together with the certbot-cloudflare if possible. 

But you improved the last months very much on the documentation and the source itself. 

nice work!
