### ISSUE TITLE
[enhancement] User-agent blocking per site

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerized-nginx#61]
Hi,
Could it be possible to add a witelist per site of user-agent ? because i facing some blocking issue for exemple with wordpresscron
or okhttp who are legite request and i then i should disable the entire "user agent" blocking system (wordpress.mydomain_BLOCK_USER_AGENT=no).

It would be wonderfull if we could define some user agent exception.

thanks

**Comment by bunkerity** [comment]
Hello @thelittlefireman,

Thanks, that's a nice idea !

**Comment by thelittlefireman** [comment]
Hello :)
Maybe we could move UA, proxies and Tor blocking to Modsecurity custom configuration ?

[https://forum.directadmin.com/threads/block-bad-robots-with-modsecurity-and-csf-in-da.60286/](https://forum.directadmin.com/threads/block-bad-robots-with-modsecurity-and-csf-in-da.60286/)
[https://linuxadmin.io/blocking-bad-useragents-modsecurity-fail2ban/](https://linuxadmin.io/blocking-bad-useragents-modsecurity-fail2ban/)

It would be easier to do site by site configuration and maybe improve log error #65

**Comment by bunkerity** [comment]
Hello @thelittlefireman,

Integrated in the last version. Thanks.
