### ISSUE TITLE
[bug] reverse-proxy-headers.conf is nerver used

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerized-nginx#62]
hi,
In multisite with reverseproxy, the file confs/site/reverse-proxy.conf seems to never be included in the config.
`grep -ril "reverse-proxy-headers.conf" ./`

this lead to some errors where websockets don't work.

moreover this proxy header files is missing some mandatory header : 
```
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
```

**Comment by bunkerity** [comment]
Fixed in the v1.2.2. Again a huge thanks :).
