### ISSUE TITLE
Remove [error] tag from LUA logs

### ISSUE THREAD

**Issue by Seculin** [bunkerity/bunkerized-nginx#68]
Hello Team, 
When i start my container using Crowdsec, i have this kind of log

reverse-system_1  | [*] Running nginx ...
reverse-system_1  | nginx: [error] [lua] init_by_lua:8: [Crowdsec] Initialisation done
reverse-system_1  | [*] Running fail2ban ...
reverse-system_1  | [*] Running crowdsec ...
reverse-system_1  | ==> /var/log/access.log <==

but i don't really understand what's meaning the error..
Thank you for your help

**Comment by bunkerity** [comment]
Hello @Seculin,

It's not an error even if you see the "error" string it just means that CrowdSec has been initialized.
The problem is when using logging with LUA it uses nginx error... Let's keep this open maybe we find an alternative to at least remove the "[error]" tag.

**Comment by Seculin** [comment]
Hello, 
Yes you are correct, it's not very clear, on the user side, if it's an error, or just an info. So it can be good if it's changed to something more clear.
Thank you so much

**Comment by bunkerity** [comment]
Hello @Seculin,

We now have "notice" instead of "error" tags on all "non critical" LUA logs. Thanks for reporting this.
