### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by Seculin** [bunkerity/bunkerized-nginx#69]
Hello guys, there is any way to add the mounting volume we have to use. I tried to discover by myself, for example, we need to mount the geoip.mmdb in /cache, but there is no documentation about it.
I'm wondering if we can have the list of all the mounting points and the purpose of each?

Thank you

**Comment by bunkerity** [comment]
Hello @Seculin,

Mounting the /cache volume is not mandatory. Just do it if you want to cache data like GeoIP DB or blacklists to avoid downloading it again when you delete/recreate containers. It's already documented [here](https://github.com/bunkerity/bunkerized-nginx#cache-data).

Let's encrypt configurations are stored in /etc/letsencrypt this is documented [here](https://github.com/bunkerity/bunkerized-nginx#run-https-server-with-automated-lets-encrypt).

If you want bunkerized-nginx to serve files just mount the web files into /www as stated [here](https://github.com/bunkerity/bunkerized-nginx#run-http-server-with-default-settings). Please note that you need a specific directory structure when using MULTISITE=yes (documented [here](https://github.com/bunkerity/bunkerized-nginx#multisite)).

And if you need to tweak ModSecurity and/or CRS settings there is some doc [here](https://github.com/bunkerity/bunkerized-nginx#modsecurity).

You also have the [examples folder](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples) showing the use of the differents volumes.

Do you think we can improve it ? Any ideas ?

**Comment by Seculin** [comment]
Thank you for your reply.
The idea is like to have a list of what we can do on the volume side. Like all what we can mount, and where by default, to have something working. 
I agree that it's like everywhere dispatched in the documentation, but perhaps having a section to define al the volume and pointing for each option/environment variable that we can enable

**Comment by bunkerity** [comment]
Hello @Seculin,

We now have an official documentation at [bunkerized-nginx.readthedocs.io](https://bunkerized-nginx.readthedocs.io/). There is also a dedicated section for the [volumes list](https://bunkerized-nginx.readthedocs.io/en/latest/volumes.html). Thanks for your suggestion and don't hesitate to open a new issue if needed.
