### ISSUE TITLE
[enhancement] Harden authentication

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerized-nginx#75]
hi,
could it be possible to add digest authentication or JWT ? 
(https://www.nginx.com/resources/wiki/modules/auth_digest/)[https://www.nginx.com/resources/wiki/modules/auth_digest/]
(https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-jwt-authentication/)[https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-jwt-authentication/]

Basic Auth is realy anoying with some js website. It will answer/popup authentication for about every request.
Moreover basic authentication send user and password as plaintext. It's ok if ssl is configure but on http only it's a security issue.

Thanks  for all :)
ps : maybe i will find some time to make an other PR

**Comment by thelittlefireman** [comment]
Or maybe we could integrate Authelia :) [https://www.authelia.com/docs/getting-started.html](https://www.authelia.com/docs/getting-started.html)

Seems to be a really good authentication framework (natively works with nginx)

**Comment by fl0ppy-d1sk** [comment]
Hey @thelittlefireman,

Authelia support is now added into bunkerized-nginx (see [docs](https://bunkerized-nginx.readthedocs.io/en/latest/environment_variables.html#authelia) and [example](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/authelia)). Thanks again for your suggestion.
