### ISSUE TITLE
add mod_security SecRemoteRules support

### ISSUE THREAD

**Issue by istvano** [bunkerity/bunkerized-nginx#77]
Hi,

Great project! I was wondering if you guys are planning to add Remote rules support for mod_security

In the following format
SecRemoteRules ${MODSEC_LICENSE} ${MODSEC_LICENSE_URL}

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#SecRemoteRules

or should this be just added via custom config?

**Comment by bunkerity** [comment]
Hello @istvano,

You should be able to do it via a custom config. More info [here](https://github.com/bunkerity/bunkerized-nginx#modsecurity) and from the examples [here](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples). Do not hesitate to reopen an issue if that doesn't work.
