### ISSUE TITLE
USE_PHP reference is missing?

### ISSUE THREAD

**Issue by coldhu** [bunkerity/bunkerized-nginx#79]
It is only in here, but could not find it in the reference...or is it deprecated?

REMOTE_PHP
Values : <any valid IP/hostname>
Default value :
Context : global, multisite
Set the IP/hostname address of a remote PHP-FPM to execute .php files. See **_USE_PHP_** if you want to run a PHP-FPM instance on the same container as bunkerized-nginx.

**Comment by bunkerity** [comment]
Hello @coldhu,

Yes it's depecrated. Thanks for pointing out.

**Comment by bunkerity** [comment]
Hello @coldhu,

Removed from README. Thanks again.
