### ISSUE TITLE
[enhancement] Add capability to add configuration above "server"

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerized-nginx#83]
Hi, 
Could I be possible to add another volume "/pre-server-confs" which will be set before the `server {...}` content
This could enable us to add `map`, `upstream` directive or other feature on site/multisite.

Something like this :

```
%PRE_SERVER_CONF%
server {
	%FASTCGI_PATH%
	%SERVER_CONF%
	%PROXY_REAL_IP%
	%MAIN_LUA%
        ...
```
 
Thanks a lot

**Comment by thelittlefireman** [comment]
My bad, could be resolve by using `/http-confs`. But could be more clear for multisite config with new volume, don't you think @bunkerity  ?

**Comment by bunkerity** [comment]
Hello @thelittlefireman,

Integrated in the last version. Thanks.
