### ISSUE TITLE
[enhancement] add whitelisting of BLOCK_USER_AGENT by ip

### ISSUE THREAD

**Issue by zherdev-artem** [bunkerity/bunkerized-nginx#84]
Hello!
It will be great not only to disable the check user agent on reverse proxy but also to have the option to add some whitelist by IP.
My API user-agent is blocking now by BLOCK_USER_AGENT, but I don't want to disable it at all, just want to add my IP to the whitelist and it won`t block.

Thanks

**Comment by thelittlefireman** [comment]
#61

**Comment by bunkerity** [comment]
Hello @zherdev-artem,

The IP listed [WHITELIST_IP_LIST](https://github.com/bunkerity/bunkerized-nginx#custom-whitelisting) should be [whitelisted before the User-Agent check](https://github.com/bunkerity/bunkerized-nginx/blob/master/confs/site/main-lua.conf#L61). Anyway, starting with v1.2.3, you can use the [WHITELIST_USER_AGENT](https://github.com/bunkerity/bunkerized-nginx#custom-whitelisting) parameter too.

Can you try the last version and provide your full command/compose and logs ?

**Comment by bunkerity** [comment]
Closing this because we lack of information. Don't hesitate to reopen it if needed.
