### ISSUE TITLE
Usage with userns-remap docker feature ?

### ISSUE THREAD

**Issue by eimfach** [bunkerity/bunkerized-nginx#89]
I use the [userns-remap](https://docs.docker.com/engine/security/userns-remap) feature to remap the user ids in the nginx container. However, this does not work with the volumes required for this image: (docker-compose.yml):

```
     volumes:
         ./ssl:/etc/letsencrypt:ro
         ./server-confs:/server-confs:ro
```
Is there another way to do this ? (copy these folders and mount them internally ?)... I assume that the `ssl` folder is for sharing the certificates with the host ? So if I omit the usage of volumes and copy these folders instead, what would be the downsides of this ?

The Docker docs say [this](https://docs.docker.com/engine/security/userns-remap/#prerequisites):

> This re-mapping is transparent to the container, but introduces some configuration complexity in situations where the container needs access to resources on the Docker host, such as bind mounts into areas of the filesystem that the system user cannot write to. From a security standpoint, it is best to avoid these situations.

Therefore I do not really want to privilege the containers id 0 root user (by creating rw access to the mapped host user) to read and write those mounted file if possible ...

**Comment by zherdev-artem** [comment]
Hi, if you have some permission denied issues with the mounting of volumes in remap mode or with users inside docker, read this answer from [stackoverflow.](https://stackoverflow.com/questions/35291520/docker-and-userns-remap-how-to-manage-volume-permissions-to-share-data-betwee)

The main idea is to create the right user's permission on docker.

You need to create a host user subid which relative to docker user id. After you need chown user on the host.

I use this code setup.

```
adduser --gecos "" --uid 6000 --disabled-login --disabled-password --no-create-home --quiet --shell=/bin/false dockermap

groupadd -g 600000 dm-root

useradd -M -u 600000 -s /bin/false -g dm-root dm-root

# Edit auto-generated subordinate ID ranges in /etc/subuid and /etc/subgid files
sed -i 's/dockermap:165536/dockermap:600000/g' /etc/subuid
sed -i 's/dockermap:165536/dockermap:600000/g' /etc/subgid

cat <<EOF > /etc/docker/daemon.json
{
  "userns-remap": "dockermap"
}
EOF

systemctl restart docker
```

After that, you will have dockermap user which will correspond to nobody user on docker, and dm-root which will root on docker.

For me it is fine works with user rights of drwxr-x--- and owner dm-root:600101 for SSL folder in this particular case.

**Comment by bunkerity** [comment]
Hello @eimfach,

Starting with the v1.2.3, the container is not running as root anymore. It runs as an unprivileged user with uid/gid 101. You should, in theory, be able to use the userns remap feature. I will try it when I have time.

**Comment by eimfach** [comment]
Back then, I did setup up my server without any shared folder because mapping privileges to the container:

> ... introduces some configuration complexity in situations where the container needs access to resources on the Docker host ... From a security standpoint, it is best to avoid these situations.

That was basically my solution to the problem.

I think it is a good improvement to run it unprivileged ! Can't test the new version however, system runs ;)

**Comment by bunkerity** [comment]
Hello @eimfach,

I've added some doc about using userns remap with bunkerized-nginx to the README ([see here](https://github.com/bunkerity/bunkerized-nginx#hardening)). Thanks again for your suggestion.
