### ISSUE TITLE
compile.sh is insecure

### ISSUE THREAD

**Issue by vanpelt** [bunkerity/bunkerized-nginx#9]
The download of the nginx source with wget isn't being verified against a known checksum.  Also, all of the public git repos are being checked out without verifying their content.  If one of the repos was compromised, or worse someone compromised the DNS server that your docker build server uses the image would be PWNed.

**Comment by bunkerity** [comment]
Hello @vanpelt, fix has been integrated in version [1.1.0](https://github.com/bunkerity/bunkerized-nginx/releases/tag/v1.1.0).

We now check that the downloaded sources are GPG signed with official nginx keys. Public git repos are now cloned with a fixed SHA1 commit (process will exit if the commit can't be found) in case they have been hijacked. Feel free to open a new issue if you think we can improve it.
