### ISSUE TITLE
[enhancement] add capability to add a custom header on reverse proxy setting

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerized-nginx#97]
hi,
Could it be possible to add the capability to add a custom header to a reverse proxy ?

for exemple i would like to add `add_header Access-Control-Allow-Origin "https://geekflare.dev";` in the following reverse proxy :
```
- home.mydomain_REVERSE_PROXY_URL=/
- home.mydomain_REVERSE_PROXY_WS=yes
- home.mydomain_REVERSE_PROXY_HOST=http://localhost:8123/
```

something like this would be great : 

```
- home.mydomain_REVERSE_PROXY_CUSTOM_HEADER=Access-Control-Allow-Origin 'https://geekflare.dev';
```

the best would be if we could add multiple headers separated by a `;` :
 
```
- home.mydomain_REVERSE_PROXY_CUSTOM_HEADER=header1 'https://geekflare.dev'; header2 'blabla'; ...
```

**Comment by bunkerity** [comment]
Hey @thelittlefireman,

Should be integrated in the last 1.2.3 version. Thanks.
