### ISSUE TITLE
Automated Let's Encrypt with CloudFlare

### ISSUE THREAD

**Issue by ptr1337** [bunkerity/bunkerized-nginx#99]
Hey, 

since youre already using CertBot, there should be a easy way to implement that in to your project. 
Since many guys probally using Cloudflare as a extra security layer for not leaking the ip or anything else. 

ENV=APITOKEN (NOT GLOBAY KEY PLS) :D and that should be mostly all. 

Ill take a watch later if i find a easy implementation. 

Regards.

**Comment by bunkerity** [comment]
Hi @ptr1337,

What about using the [certbot/certbot-cloudflare](https://hub.docker.com/r/certbot/dns-cloudflare) ? You have an example [here](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/certbot-wildcard) with the "classical" DNS challenge. I will try to make one with certbot/certbot-cloudflare when I have time.

**Comment by ptr1337** [comment]
I switched now to your proxy, but in im not getting the real ip ? 

Tried with Proxy Header, WhitelistIP and so on. but i dont get it.

**Comment by bunkerity** [comment]
Hello @ptr1337,

Can you share more information please ? What you are trying to achieve, your architecture (e.g. : behind a reverse proxy ? as a reverse proxy ? both ?), your environment variables, logs, things you tried, commands, compose, ... There is an issue template for bugs, maybe you should open a new one ?

**Comment by bunkerity** [comment]
From what I understand, you are trying to use bunkerized-nginx behind CloudFlare and get the real IP of the clients ? If that's the case, you should have a look at :  
- `PROXY_REAL_IP` : set it to **yes** to activate the realip module
- `PROXY_REAL_IP_FROM` : list of **IP / subnets of CloudFlare** to trust (maybe [that](https://www.cloudflare.com/ips/) ?)
- `PROXY_REAL_IP_HEADER` : the header used by CloudFlare containing the real IP (default is set to **X-Forwarded-For**, looks like [CloudFlare is sending that header](https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-))

**Comment by ptr1337** [comment]
My bad .. I used the wrong configuration options. 

I’ll take a watch later, but that should work!

**Comment by bunkerity** [comment]
Hey @ptr1337,

Here is a gift for you : [certbot-cloudflare example](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/certbot-cloudflare). Feel free to test it and report any bug.

**Comment by bunkerity** [comment]
@ptr1337 : one gift is not enough, here is [another one](https://www.bunkerity.com/web-security-at-almost-no-cost-cloudflare-free-plan-with-bunkerized-nginx/).

**Comment by ptr1337** [comment]
Hey @fl0ppy-d1sk ,

I read the dev branch since long time and considering to use it with the webui. 
Is it possible to use the webui + cloudflare zertificates ? 
And how about multiple websites ? 


Regards and thanks for your great work!

**Comment by fl0ppy-d1sk** [comment]
Hello @ptr1337,

I won't recommend using the dev branch, everything is moving from day to day, it's far from stable. But maybe you can stick to a specific commit which is working for you or wait until the next release :).

It should work with cloudflare and multiple websites but you'll need to "mix" both configurations (e.g. : [certbot-cloudflare](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/certbot-cloudflare) and [web-ui](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/web-ui)). The web UI is just a web service after all and you can use bunkerized-nginx as a reverse proxy in front of it.

**Comment by ptr1337** [comment]
Alright. 

i waiting for the stable release from the dev branch. And then gonna test it. Thank you!

Then i think my final switch is comming!
